name: Build necora_auth
permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        run: rustup update stable
      - name: Run tests
        run: cargo test --verbose

  build:
    needs: test
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        run: rustup update stable

      - name: Install cross
        run: cargo install cross

      - name: Set version and binary name
        run: |
          TARGET=${{ matrix.target }}
          VERSION=${GITHUB_REF#refs/tags/}        
          BINARY_NAME="${{ github.event.repository.name }}-${TARGET}-${VERSION}
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TARGET=$TARGET" >> $GITHUB_ENV

      - name: Build with cross
        run: |
          cross build --release --target $TARGET
          cp target/$TARGET/release/${{ github.event.repository.name }}$EXT $BINARY_NAME

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BINARY_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}